export const questionBank = [
    {
        id: "1",
        category: 'Tenaga Ahli',
        question: 'Jabatan Anda Saat Ini ?',
        answer: '',
        type: 'text',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "2",
        category: 'Tenaga Ahli',
        question: 'Tuliskan kompetensi yang Anda miliki dan memiliki kontribusi dalam organisasi Anda',
        answer: '',
        type: 'text',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "3",
        question: 'Tuliskan dengan detail pekerjaan yang saat ini dilakukan selama menjadi Tenaga Ahli dilingkungan Pemprov Banten',
        answer: '',
        type: 'text',
        category: 'Tenaga Ahli',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "4",
        question: 'Tuliskan kendala-kendala yang dihadapi yang Anda hadapi selama ini',
        answer: '',
        type: 'text',
        category: 'Tenaga Ahli',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "5",
        question: 'Apakah harapan Anda terhadap organisasi Anda ke depannya',
        answer: '',
        type: 'text',
        category: 'Tenaga Ahli',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "6",
        question: 'Bagaimana harapan Anda, organisasi kedepan seperti apa, uraikan dengan detail ',
        answer: '',
        type: 'text',
        category: 'Kepala Dinas, Sekretaris dan Kabid',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "7",
        question: 'Bagaimana harapan Anda selaku pimpinan kepada terhadap TA ( Tenaga Ahli yg dibutuhkan) ?',
        answer: '',
        type: 'text',
        category: 'Kepala Dinas, Sekretaris dan Kabid',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "8",
        question: 'Kendala yang dihadapi oleh Organisasi/ Bagian yg Bapak/ Ibu Pimpin seperti apa',
        answer: '',
        type: 'text',
        category: 'Kepala Dinas, Sekretaris dan Kabid',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    },
    {
        id: "9",
        question: 'Kendala yang dihadapi oleh Bapak/ Ibu pimpinan terhadap Tenaga Ahli, seperti apa saja',
        answer: '',
        type: 'text',
        category: 'Kepala Dinas, Sekretaris dan Kabid',
        required: true,
        createdAt: new Date(Date.now()).toLocaleDateString(),
        updatedAt: new Date(Date.now()).toLocaleDateString(),
    }
]